#!/usr/bin/env node
/**
 * scripts/native-shell.mjs
 *
 * Generates dist/client/index.html from the TanStack Start build manifest.
 * Must be run AFTER `vite build` (which produces .output/public/assets/ and
 * .output/server/assets/_tanstack-start-manifest_v-*.js).
 *
 * Usage:
 *   node scripts/native-shell.mjs
 *
 * Called automatically by `bun run native:build`.
 *
 * Asset paths are written as relative (./assets/…) so they resolve under
 * both file:// (Electron production) and http:// (Vite dev / CF Worker).
 *
 * In addition, the generated client bundle is patched for the packaged
 * Electron shell:
 *   - TanStack Start's client entry uses hydrateRoot(document, ...), which
 *     fails when the static shell contains injected bootstrap script tags.
 *     We rewrite it to createRoot(document).render(...) for client-only
 *     rendering in the native shell.
 *   - A minimal window.$_TSR bootstrap is injected so StartClient can enter
 *     SPA mode and call router.load() without SSR dehydrated state.
 */

import { readFileSync, writeFileSync, readdirSync, cpSync, rmSync } from "fs";
import { join } from "path";

const distClient = "dist/client";
const buildPublic = ".output/public";
const buildServer = ".output/server";

// Ensure dist/client is a fresh copy of the built public assets.
rmSync(distClient, { recursive: true, force: true });
cpSync(buildPublic, distClient, { recursive: true });

// Find the manifest file (hash changes on every build).
const manifestFile = readdirSync(buildServer).find((f) =>
  f.startsWith("_tanstack-start-manifest_v-"),
);
if (!manifestFile) {
  throw new Error(
    `[native-shell] No TanStack Start manifest found in ${buildServer}. ` +
      `Run 'bun run build' first.`,
  );
}

// Parse the manifest to extract clientEntry and stylesheet assets.
const manifestContent = readFileSync(join(buildServer, manifestFile), "utf8");

// Extract clientEntry (the main JS bundle path).
const clientEntryMatch = manifestContent.match(/clientEntry:\s*["']([^"']+)["']/);
if (!clientEntryMatch) {
  throw new Error("[native-shell] Could not find clientEntry in manifest.");
}
// Manifest returns absolute paths like "/assets/index-C918henm.js".
// Convert to relative "./assets/…" so they resolve under file:// (Electron).
const clientEntry = "." + clientEntryMatch[1]; // e.g. "./assets/index-C918henm.js"

// Extract all stylesheet href values from the root route assets.
const stylesheetMatches = [
  ...manifestContent.matchAll(/rel:\s*["']stylesheet["'][^}]*href:\s*["']([^"']+)["']/g),
];
const stylesheets = stylesheetMatches.map((m) => "." + m[1]);

// Also pick up any CSS files directly in dist/client/assets that aren't in the manifest.
const allClientAssets = readdirSync(`${distClient}/assets`);
const cssFiles = allClientAssets
  .filter((f) => f.endsWith(".css"))
  .map((f) => `./assets/${f}`)
  .filter((href) => !stylesheets.includes(href)); // avoid duplicates

const allStylesheets = [...stylesheets, ...cssFiles];

const styleLinks = allStylesheets
  .map((href) => `    <link rel="stylesheet" href="${href}" type="text/css" />`)
  .join("\n");

// Minimal bootstrap for the Electron packaged shell. TanStack Start's client
// entry calls window.$_TSR?.h() and router.hydrate() expects a dehydrated
// router payload. We provide an empty SPA-fallback payload so the client
// treats this as SPA mode, keeps the root match pending until router.load()
// finishes, and renders the real UI instead of a blank window.
const tsrBootstrap = `    <script>
      window.$_TSR = window.$_TSR || {};
      window.$_TSR.h = window.$_TSR.h || function () {};
      window.$_TSR.e = window.$_TSR.e || function () {};
      window.$_TSR.c = window.$_TSR.c || function () {};
      window.$_TSR.p = window.$_TSR.p || function (script) {
        (window.$_TSR.buffer = window.$_TSR.buffer || []).push(script);
      };
      window.$_TSR.buffer = window.$_TSR.buffer || [];
      window.$_TSR.router = {
        manifest: { routes: { __root__: { assets: [], preloads: [] } } },
        matches: [],
        lastMatchId: "",
      };
      window.$_TSR.initialized = true;
    </script>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Edgecase Cockpit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="A provider-native AI chat console \u2014 local-first, multi-provider." />
    <!--
      Native shell — generated by scripts/native-shell.mjs.
      Do not edit by hand. Re-run 'bun run native:build' to regenerate.
      clientEntry: ${clientEntry}
    -->
${styleLinks}
${tsrBootstrap}
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${clientEntry}"></script>
  </body>
</html>
`;

writeFileSync(`${distClient}/index.html`, html, "utf8");

// Patch the client bundle to use client-only rendering (createRoot) instead
// of hydration (hydrateRoot). The static native shell has injected bootstrap
// script tags that React's hydrateRoot would mismatch against.
const bundlePath = `${distClient}${clientEntry.replace(/^\./, "")}`;
let bundle = readFileSync(bundlePath, "utf8");
const originalHydrate = "hydrateRoot(document,";
const replacementRender = "createRoot(document).render(";
if (bundle.includes(originalHydrate)) {
  bundle = bundle.replaceAll(originalHydrate, replacementRender);
  writeFileSync(bundlePath, bundle, "utf8");
  console.log(`[native-shell] Patched ${bundlePath} for client-only render`);
} else if (!bundle.includes(replacementRender)) {
  console.warn(
    `[native-shell] Could not find hydrateRoot(document,...) in ${bundlePath}; ` +
      `client-only patch may be incomplete.`,
  );
}

console.log(`[native-shell] Wrote ${distClient}/index.html`);
console.log(`  clientEntry: ${clientEntry}`);
console.log(`  stylesheets: ${allStylesheets.join(", ")}`);
