#!/usr/bin/env node
/**
 * scripts/native-shell.mjs
 *
 * Generates dist/client/index.html from the TanStack Start build manifest.
 * Must be run AFTER `vite build` (which produces dist/client/assets/ and
 * dist/server/assets/_tanstack-start-manifest_v-*.js).
 *
 * Usage:
 *   node scripts/native-shell.mjs
 *
 * Called automatically by `bun run native:build`.
 *
 * Asset paths are written as relative (./assets/…) so they resolve under
 * both file:// (Electron production) and http:// (Vite dev / CF Worker).
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const distClient = "dist/client";
const distServer = "dist/server/assets";

// Find the manifest file (hash changes on every build).
const manifestFile = readdirSync(distServer).find((f) =>
  f.startsWith("_tanstack-start-manifest_v-"),
);
if (!manifestFile) {
  throw new Error(
    `[native-shell] No TanStack Start manifest found in ${distServer}. ` +
      `Run 'bun run build' first.`,
  );
}

// Parse the manifest to extract clientEntry and stylesheet assets.
const manifestContent = readFileSync(join(distServer, manifestFile), "utf8");

// Extract clientEntry (the main JS bundle path).
const clientEntryMatch = manifestContent.match(/clientEntry:\s*["']([^"']+)["']/);
if (!clientEntryMatch) {
  throw new Error("[native-shell] Could not find clientEntry in manifest.");
}
// Manifest returns absolute paths like "/assets/index-C918henm.js".
// Convert to relative "./assets/…" so they resolve under file:// (Electron).
const clientEntry = "." + clientEntryMatch[1]; // e.g. "./assets/index-C918henm.js"

// Extract all stylesheet href values from the root route assets.
const stylesheetMatches = [
  ...manifestContent.matchAll(/rel:\s*["']stylesheet["'][^}]*href:\s*["']([^"']+)["']/g),
];
const stylesheets = stylesheetMatches.map((m) => "." + m[1]);

// Also pick up any CSS files directly in dist/client/assets that aren't in the manifest.
const allClientAssets = readdirSync(`${distClient}/assets`);
const cssFiles = allClientAssets
  .filter((f) => f.endsWith(".css"))
  .map((f) => `./assets/${f}`)
  .filter((href) => !stylesheets.includes(href)); // avoid duplicates

const allStylesheets = [...stylesheets, ...cssFiles];

const styleLinks = allStylesheets
  .map((href) => `    <link rel="stylesheet" href="${href}" type="text/css" />`)
  .join("\n");

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Edgecase Cockpit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="A provider-native AI chat console \u2014 local-first, multi-provider." />
    <!--
      Native shell — generated by scripts/native-shell.mjs.
      Do not edit by hand. Re-run 'bun run native:build' to regenerate.
      clientEntry: ${clientEntry}
    -->
${styleLinks}
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${clientEntry}"></script>
  </body>
</html>
`;

writeFileSync(`${distClient}/index.html`, html, "utf8");
console.log(`[native-shell] Wrote ${distClient}/index.html`);
console.log(`  clientEntry: ${clientEntry}`);
console.log(`  stylesheets: ${allStylesheets.join(", ")}`);
