/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIdRouteImport } from './routes/thread.$id'
import { Route as ApiProxyDetectRouteImport } from './routes/api/proxy/detect'
import { Route as ApiProxyChatRouteImport } from './routes/api/proxy/chat'
import { Route as ApiKeysSetRouteImport } from './routes/api/keys/set'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/thread/$id',
  path: '/thread/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyDetectRoute = ApiProxyDetectRouteImport.update({
  id: '/api/proxy/detect',
  path: '/api/proxy/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyChatRoute = ApiProxyChatRouteImport.update({
  id: '/api/proxy/chat',
  path: '/api/proxy/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysSetRoute = ApiKeysSetRouteImport.update({
  id: '/api/keys/set',
  path: '/api/keys/set',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/thread/$id': typeof ThreadIdRoute
  '/api/keys/set': typeof ApiKeysSetRoute
  '/api/proxy/chat': typeof ApiProxyChatRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/thread/$id': typeof ThreadIdRoute
  '/api/keys/set': typeof ApiKeysSetRoute
  '/api/proxy/chat': typeof ApiProxyChatRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/thread/$id': typeof ThreadIdRoute
  '/api/keys/set': typeof ApiKeysSetRoute
  '/api/proxy/chat': typeof ApiProxyChatRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/images'
    | '/library'
    | '/settings'
    | '/videos'
    | '/thread/$id'
    | '/api/keys/set'
    | '/api/proxy/chat'
    | '/api/proxy/detect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/images'
    | '/library'
    | '/settings'
    | '/videos'
    | '/thread/$id'
    | '/api/keys/set'
    | '/api/proxy/chat'
    | '/api/proxy/detect'
  id:
    | '__root__'
    | '/'
    | '/images'
    | '/library'
    | '/settings'
    | '/videos'
    | '/thread/$id'
    | '/api/keys/set'
    | '/api/proxy/chat'
    | '/api/proxy/detect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImagesRoute: typeof ImagesRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  VideosRoute: typeof VideosRoute
  ThreadIdRoute: typeof ThreadIdRoute
  ApiKeysSetRoute: typeof ApiKeysSetRoute
  ApiProxyChatRoute: typeof ApiProxyChatRoute
  ApiProxyDetectRoute: typeof ApiProxyDetectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$id': {
      id: '/thread/$id'
      path: '/thread/$id'
      fullPath: '/thread/$id'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/detect': {
      id: '/api/proxy/detect'
      path: '/api/proxy/detect'
      fullPath: '/api/proxy/detect'
      preLoaderRoute: typeof ApiProxyDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/chat': {
      id: '/api/proxy/chat'
      path: '/api/proxy/chat'
      fullPath: '/api/proxy/chat'
      preLoaderRoute: typeof ApiProxyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/set': {
      id: '/api/keys/set'
      path: '/api/keys/set'
      fullPath: '/api/keys/set'
      preLoaderRoute: typeof ApiKeysSetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImagesRoute: ImagesRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  VideosRoute: VideosRoute,
  ThreadIdRoute: ThreadIdRoute,
  ApiKeysSetRoute: ApiKeysSetRoute,
  ApiProxyChatRoute: ApiProxyChatRoute,
  ApiProxyDetectRoute: ApiProxyDetectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
